esphome:
  name: <name> 
  platform: ESP8266
  board: esp01_1m

# wifi to connect to
wifi:
  ssid: "<ssid>"
  password: "<password>"
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "<Fallback Hotspot SSID>"
    password: "<fallback hotspot password>"

#enable captive portal for hotspot
captive_portal:

# disable logging and serial connection. baud_rate/serial connection is used by tuyamcu
logger:
  baud_rate: 0
  level: NONE

# enable OTA
ota:

#MQTT
# disable discovery since we are not using HA
mqtt:
  broker: <broker IP address>
  discovery: false
  
# Enable web server
web_server:
  port: 80

# My dimmer used this hardware serial port
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable light and dimmer
light:
  - platform: "tuya"
    name: "<dimmer name>"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000
    state_topic: "<MQTT topic to post state to>"
    command_topic: "<MQTT topic to listen for commands>"
    retain: false
